name: Daily RETWIN ETL

# Run daily at 22:15 UTC
on:
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  run-etl:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run ENTSOE ETL
      - name: Run ENTSOE ETL
        run: python etl.py
        env:
          # PostgreSQL / Azure
          AZURE_PG_HOST: ${{ secrets.AZURE_PG_HOST }}
          AZURE_PG_DB: ${{ secrets.AZURE_PG_DB }}
          AZURE_PG_USER: ${{ secrets.AZURE_PG_USER }}
          AZURE_PG_PASSWORD: ${{ secrets.AZURE_PG_PASSWORD }}

          # ENTSOE API
          SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}

          # Email
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
